--["PCCustomerInlineSearch","PCCustomer.Processes.InlineSearch","inlineSearch","Customer","Y","Y","Y","Inline Search"]
INSERT INTO EVA_PROCESS_DESCRIPTOR (ID, ENV_ID, NAME, REPOSITORY_PATH, CONFIG_PROCESS_ID, IS_DELETED,TYPE) VALUES (
@PD.PCCustomerInlineSearch, -- ID
@ENV.Dflt, -- ENV_ID
'PCCustomerInlineSearch', -- NAME
'PCCustomer.Processes.InlineSearch', -- REPOSITORY_PATH
NULL, --CONFIG_PROCESS_ID
'N', --IS_DELETED
0 --TYPE
);

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'ProcessDescriptorED', -- OBJECT_TYPE
'PCCustomerInlineSearch__PCCustomer.Processes.InlineSearch | replace(".","/")', -- OBJECT_INSTANCE
$PD.PCCustomerInlineSearch, -- OBJECT_VERSION
'displayName', -- FIELD_NAME
'en-US', -- LOCALE
'default', -- LOOKUP_LOCALE
'PCCustomerInlineSearch', -- TEXT
'N'
);

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'ProcessDescriptorED', -- OBJECT_TYPE
'PCCustomerInlineSearch__PCCustomer.Processes.InlineSearch | replace(".","/")', -- OBJECT_INSTANCE
$PD.PCCustomerInlineSearch, -- OBJECT_VERSION
'description', -- FIELD_NAME
'en-US', -- LOCALE
'default', -- LOOKUP_LOCALE
'PCCustomerInlineSearch', -- TEXT
'N'
);

INSERT INTO EVA_PROCESS_DESC_REFERENCE (ID, PROCESS_DESCRIPTOR_ID, PROCESS_DESCRIPTOR_ENV_ID, CONFIG_ID, IS_SHARED) VALUES (
@PDR.PCCustomerInlineSearch, --ID
@PD.PCCustomerInlineSearch, --PROCESS_DESCRIPTOR_ID
@ENV.Dflt, --PROCESS_DESCRIPTOR_ENV_ID
NULL, --CONFIG_ID
'N' -- IS_SHARED
);

INSERT INTO EVA_VERB (ID, NAME, PROCESS_DESC_REF_ID, ENTITY_DEF_ID, ENTITY_DEF_ENV_ID, IS_INSTANCE, IS_DEFAULT, IS_INSTANCE_DEFAULT, IS_USER_VISIBLE) VALUES (
@V.PCCustomerInlineSearch, --ID
'inlineSearch', -- NAME
@PDR.PCCustomerInlineSearch, --PROCESS_DESC_REF_ID
@ED.Customer, -- ENTITY_DEF_ID
@ENV.Dflt, -- ENTITY_DEF_ENV_ID
'Y', --IS_INSTANCE
'N', -- IS_DEFAULT
'Y', -- IS_INSTANCE_DEFAULT
'Y' -- IS_USER_VISIBLE
);

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'VerbED',-- OBJECT_TYPE
'CustomerED__PCCustomerInlineSearch',-- OBJECT_INSTANCE
$V.PCCustomerInlineSearch,-- OBJECT_VERSION
'displayName',-- FIELD_NAME
'en-US',-- LOCALE
'default', -- LOOKUP_LOCALE
'Inline Search', -- TEXT
'N'
);

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'VerbED',-- OBJECT_TYPE
'CustomerED__PCCustomerInlineSearch',-- OBJECT_INSTANCE
$V.PCCustomerInlineSearch,-- OBJECT_VERSION
'description', -- FIELD_NAME
'en-US',-- LOCALE
'default', -- LOOKUP_LOCALE
'Inline Search', -- TEXT
'N'
);
