--["Finance","System"]
INSERT INTO EVA_CATEGORY (ID,ENV_ID,PARENT_CATEGORY_ID,PARENT_CATEGORY_ENV_ID,ENTITY_DEF_ID,ENTITY_DEF_ENV_ID,RELEASE_ID,SYSTEM_NAME)
VALUES (
	@EC.Finance, --ID
	@ENV.Dflt, --ENV_ID
	@EC.System, --PARENT_CATEGORY_ID
	@ENV.Dflt, --PARENT_CATEGORY_ENV_ID
	@ED.EntityDefinition, --ENTITY_DEF_ID
	@ENV.Dflt, --ENTITY_DEF_ENV_ID
	@RELEASE.ID,
	'Categories->System->Finance' --SYSTEM_NAME
       );
