--{"base_entity_id":"Contact","child_object_path":"PRJContact.Implementation.Contact.PRJContact","child_inteface_path":"PRJContact.API.EIPRJContact","locale":"en-US"}
INSERT INTO EVA_ENTITY_DEFINITION (ID, ENV_ID, NAME, UUID, TYPE_UUID, TYPE_ID, TYPE_ENV_ID, LOGICAL_OBJ_PATH, INTERFACE_PATH, SUPER_ENTITY_DEFINITION, SUPER_ENTITY_DEFINITION_ENV_ID, IS_DELETED, IS_BASIC, SUPPORTS_READONLY,IS_EXPANDABLE,ICON_PATH, INSTANCE_ICON_PATH) VALUES (
@ED.BaseContact, -- ID
@ENV.Dflt, -- ENV_ID
'BaseContactED', -- NAME
'BaseContactED', -- UUID
'BaseContactED', -- TYPE_UUID
@ET.BaseContact, -- TYPE_ID
@ENV.Dflt, -- TYPE_ENV_ID
'CoreContactHistory.Implementation.Contact.Contact', -- LOGICAL_OBJECT_PATH
'CoreContactHistory.API.Interfaces.EIContact', -- INTERFACE_PATH
NULL, -- SUPER_ENTITY_DEFINITION
@ENV.Dflt, -- SUPER_ENTITY_DEFINITION_ENV_ID
'N', -- IS_DELETED
'Y', -- IS_BASIC
'Y', -- SUPPORTS_READ_ONLY
'Y', --IS_EXPANDABLE
NULL, -- ICON_PATH
NULL -- INSTANCE_ICON_PATH
);
INSERT INTO EVA_CATEGORY_ENTRY(CATEGORY_ID, CATEGORY_ENV_ID, ENTITY_ID, ENTITY_ENV_ID) VALUES (
  @EC.SystemContact, -- CATEGORY_ID
  @ENV.Dflt, -- CATEGORY_ENV_ID
  @ED.BaseContact, -- ENTITY_ID
  @ENV.Dflt -- ENTITY_ENV_ID
  );

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'EntityDefinitionED', -- OBJECT_TYPE
'BaseContactED', -- OBJECT_INSTANCE
@ED.BaseContact, -- OBJECT_VERSION
'displayName', -- FIELD_NAME
'en-US', -- LOCALE
'default', -- LOOKUP_LOCALE
'Base Contact', --TEXT
'N' --IS_DELETED
);
INSERT INTO LOCALISED_FIELD (OBJECT_TYPE, OBJECT_INSTANCE, OBJECT_VERSION, FIELD_NAME, LOCALE, LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES (
'EntityDefinitionED', -- OBJECT_TYPE
'BaseContactED', -- OBJECT_INSTANCE
@ED.BaseContact, -- OBJECT_VERSION
'description', -- FIELD_NAME
'en-US', -- LOCALE
'default', -- LOOKUP_LOCALE
'Base A specific contact two parties', --TEXT
'N' --IS_DELETED
);
UPDATE EVA_ENTITY_DEFINITION
SET (LOGICAL_OBJ_PATH, INTERFACE_PATH, SUPER_ENTITY_DEFINITION, SUPER_ENTITY_DEFINITION_ENV_ID) = ('PRJContact.Implementation.Contact.PRJContact', 'PRJContact.API.EIPRJContact', @ED.BaseContact, @ENV.Dflt) WHERE ID = @ED.Contact AND ENV_ID = @ENV.Dflt AND RELEASE_ID = @RELEASE.ID;
